Repository godaddy/godaddy.github.io, pull requests merged in 2018-06, with the labels that each got.

#46 feat(post): add an optional, full-bleed featured image to the blog posts
  _layouts/post.html
  _posts/2018-04-04-isomorphic-asset-system-for-react-and-react-native.md
  _posts/2018-05-15-jiractl.md
  _stylesheets/layout/_post.scss
Labels: ui

#45 feat(post): add an optional drop cap feature for blog post layouts
  _posts/2018-02-22-announcing-terminus.md
  _posts/2018-04-02-introducing-eslint-plugin-i18n-json.md
  _posts/2018-05-02-kubernetes-introduction-for-developers.md
  _posts/2018-05-15-jiractl.md
  _stylesheets/base/_typography.scss
Labels: ui

#42 feat(post): update the social share and author widgets
  _includes/block/scripts.html
  _includes/component/author-panel.html
  _includes/component/social-share.html
  _layouts/post.html
  _posts/2018-06-06-cicd-best-practices.md
  _stylesheets/appstyles.scss
  _stylesheets/base/_reset.scss
  _stylesheets/components/_authors-panel.scss
Labels: ui, ux

#47 fix(post): remove duplicate authors panel from layout
  _layouts/post.html
  _posts/2018-05-15-jiractl.md
Labels: bug

#51 fix(home): resolve bug preventing GitHub corner widget from rendering
  _layouts/home.html
Labels: bug

#49 feat(projects): make featured projects searchable
  _data/projects.json
  _includes/block/scripts.html
  _includes/component/project-card.html
  _includes/component/project-search.html
  _includes/scripts/filter-projects.js
  featured-projects.html
Labels: enhancement, ux

#50 feat(projects): add more featured projects
  _data/projects.json
  _includes/component/project-search.html
  _includes/scripts/filter-projects.js
Labels: content

#54 Add Google Webmaster Tools site verification page
  google31504ad6813eb6a4.html
Labels: seo

#56 revert(SEO): revert temporary Google verification pages
  google31504ad6813eb6a4.html
  google951d34d35bc8d73a.html
Labels: seo

#53 feat(atom): enable the Atom (RSS) feed plugin
  _config.yml
  _includes/block/head.html
Labels: seo

#57 feat(post): jenkins build monitoring plugin
  _posts/2018-06-19-jenkins-build-monitoring-plugin.md
  assets/images/jenkmagic.png
  assets/images/monitoring-plugin/flowgraph-table.png
  assets/images/monitoring-plugin/flownode-table.png
  assets/images/monitoring-plugin/github-autostatus-design.png
  assets/images/monitoring-plugin/pr-build-page.png
Labels: content
